### ISSUE TITLE
Optimizando

### ISSUE THREAD

**Issue by hymsoft** [Rojo/Respuestas-de-Aprende-a-Programar#12]
Hola, vengo siguiendo tu codigo y creo que de esta manera es mas corto, ya que singular solo seria una vez (1 elefante) el resto serian todos plurales. De esta forma no evaluo 100 veces la condicion
if elefantes == 1
    puts elefantes.to_s + rima_
...
end

--- Mi codigo ---
elefantes = 1
puts(elefantes.to_s + ' elefante se balanceaba sobre la tela de una araña.')
elefantes = elefantes + 1

while elefantes < 100
	puts(elefantes.to_s + ' elefantes se balanceaban sobre la tela de una araña.')
	elefantes = elefantes + 1 
end

**Comment by Rojo** [comment]
@hymsoft Es cierto, lo actualizaré.

**Comment by Rojo** [comment]
Corregido en bd3b35830c70b2250f0335216953f59e88239425.
